## Colors configuration
colors:
  # Default colors
  primary:
    background: '#0C0808'
    foreground: '#dec9cd'

  # Normal colors
  normal:
    black:   '#0C0808'
    red:     '#C15C4C'
    green:   '#D5946C'
    yellow:  '#385386'
    blue:    '#636A93'
    magenta: '#A27592'
    cyan:    '#7985AA'
    white:   '#dec9cd'

  # Bright colors
  bright:
    black:   '#9b8c8f'
    red:     '#C15C4C'
    green:   '#D5946C'
    yellow:  '#385386'
    blue:    '#636A93'
    magenta: '#A27592'
    cyan:    '#7985AA'
    white:   '#dec9cd'
